---
dist: trusty

language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

addons:
  apt:
    packages:
      - musl-tools

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install: rustup target install x86_64-unknown-linux-musl
install: make release
script: cargo test --verbose

notifications:
  email:
    on_success: never
    on_failure: never
